/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as dashboardPerfilImport } from './routes/(dashboard)/Perfil'
import { Route as dashboardOfertasImport } from './routes/(dashboard)/Ofertas'
import { Route as authRegisterImport } from './routes/(auth)/Register'
import { Route as authLoginImport } from './routes/(auth)/Login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardPerfilRoute = dashboardPerfilImport.update({
  id: '/(dashboard)/Perfil',
  path: '/Perfil',
  getParentRoute: () => rootRoute,
} as any)

const dashboardOfertasRoute = dashboardOfertasImport.update({
  id: '/(dashboard)/Ofertas',
  path: '/Ofertas',
  getParentRoute: () => rootRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/(auth)/Register',
  path: '/Register',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/Login': {
      id: '/(auth)/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/Register': {
      id: '/(auth)/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/Ofertas': {
      id: '/(dashboard)/Ofertas'
      path: '/Ofertas'
      fullPath: '/Ofertas'
      preLoaderRoute: typeof dashboardOfertasImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/Perfil': {
      id: '/(dashboard)/Perfil'
      path: '/Perfil'
      fullPath: '/Perfil'
      preLoaderRoute: typeof dashboardPerfilImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof authLoginRoute
  '/Register': typeof authRegisterRoute
  '/Ofertas': typeof dashboardOfertasRoute
  '/Perfil': typeof dashboardPerfilRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof authLoginRoute
  '/Register': typeof authRegisterRoute
  '/Ofertas': typeof dashboardOfertasRoute
  '/Perfil': typeof dashboardPerfilRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)/Login': typeof authLoginRoute
  '/(auth)/Register': typeof authRegisterRoute
  '/(dashboard)/Ofertas': typeof dashboardOfertasRoute
  '/(dashboard)/Perfil': typeof dashboardPerfilRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Login' | '/Register' | '/Ofertas' | '/Perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Login' | '/Register' | '/Ofertas' | '/Perfil'
  id:
    | '__root__'
    | '/'
    | '/(auth)/Login'
    | '/(auth)/Register'
    | '/(dashboard)/Ofertas'
    | '/(dashboard)/Perfil'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  dashboardOfertasRoute: typeof dashboardOfertasRoute
  dashboardPerfilRoute: typeof dashboardPerfilRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  dashboardOfertasRoute: dashboardOfertasRoute,
  dashboardPerfilRoute: dashboardPerfilRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)/Login",
        "/(auth)/Register",
        "/(dashboard)/Ofertas",
        "/(dashboard)/Perfil"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)/Login": {
      "filePath": "(auth)/Login.tsx"
    },
    "/(auth)/Register": {
      "filePath": "(auth)/Register.tsx"
    },
    "/(dashboard)/Ofertas": {
      "filePath": "(dashboard)/Ofertas.tsx"
    },
    "/(dashboard)/Perfil": {
      "filePath": "(dashboard)/Perfil.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
